baseURL = 'http://example.org/'
theme = "massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[params]
  # set below parameter to define a favicon
  favicon = "images/rounded-logo.svg"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.it]
  languageName = "Italian"
  title = 'JTB | The Future Haircut'
  languageCode = 'it'

[languages.en]
  languageName = "English"
  title = 'JTB | The Future Haircut'
  languageCode = 'en-us'